COLOR_FIRST = 'White'
COLOR_SECOND = 'Black'
FILE_NAMES = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
RANK_NAMES = ['1', '2', '3', '4', '5', '6', '7', '8']
PIECE_SYMBOLS = ['R', 'N', 'B', 'Q', 'K']

MENU_FILE = '&File'
MENU_BOARD = '&Board'
MENU_NEW = '&New Game'
MENU_NEW_TIP = 'Start a new game'
MENU_OPEN = '&Open Game'
MENU_OPEN_TIP = 'Open a new game'
MENU_SAVE = '&Save Game'
MENU_SAVE_TIP = 'Save the current game'
MENU_SAVEAS = '&Save Game As'
MENU_SAVEAS_TIP = 'Save the current game to a new file'
MENU_QUIT = '&Quit'
MENU_QUIT_TIP = 'Exit application'
MENU_EDITBOARD = '&Setup a position'
MENU_EDITBOARD_TIP = 'Add or remove pieces from the current position'
MENU_FLIP = '&Flip'
MENU_FLIP_TIP = 'Flip the current board'
